"""empty message

Revision ID: 420c954aec91
Revises: f434602350d1
Create Date: 2025-10-08 21:39:52.637041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420c954aec91'
down_revision = 'f434602350d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'user_id', name='unique_candidate_publication_pair')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_publication')
    # ### end Alembic commands ###
